<Project>
	<PropertyGroup>
		<UseLocalEngine>false</UseLocalEngine>
		<ClockworkEnginePath>..\..\..\clockwork-engine\ClockworkEngine\ClockworkEngine\ClockworkEngine.csproj</ClockworkEnginePath>
	</PropertyGroup>

	<ItemGroup Condition="'$(UseLocalEngine)' == 'false'">
		<PackageReference Include="ClockworkEngine" Version="*" />
	</ItemGroup>

	<ItemGroup Condition="'$(UseLocalEngine)' == 'true'">
		<ProjectReference Include="$(ClockworkEnginePath)" />
	</ItemGroup>
</Project>